### ISSUE TITLE
text_decoration svg attribute missing

### ISSUE THREAD

**Issue by LukeAllen** [mozman/svgwrite#1]
This page says the 'text-decoration' attribute is supported:
https://pythonhosted.org/svgwrite/attributes/presentation.html

But this code fails:
```
dwg.add(dwg.text("test",insert = (0, 0),font_size="30px",fill='black',
                     text_decoration='underline',
                     ))

>>> ValueError: Invalid attribute 'text-decoration' for svg-element <text>.
```

**Comment by mozman** [comment]
The linked page shows the available presentation attributes for the text element for SVG 1.1 profile.

I assume you use the SVG Tiny 1.2 profile, which does not support the text-decoration attribute.

**Comment by LukeAllen** [comment]
Oh thanks! I had started with someone else's code snippet and didn't realize that its specification of ```dwg(profile='tiny'...``` was nonstandard.
It works now that I switched to the default ```profile='full'```. Thanks for your help. (I'm closing the issue.)
