### ISSUE TITLE
Using bold and changing the font type

### ISSUE THREAD

**Issue by dbareiro** [mozman/svgwrite#10]
Hi, Manfred!

Thank you very much for developing this Python library!

I would like to know if it is possible to write bold text and changing the font type (eg DejaVu Sans). I have been researching but I have not succeeded. If it is possible, I would appreciatel if you could give me an example of how to do it.

Thanks in advance.

Regards,
Daniel

**Comment by mozman** [comment]
Hi!

Best way to use svgwrite is to learn SVG first and the try to accomplish that with svgwrite.

some links to SVG ressources:

http://commons.oreilly.com/wiki/index.php/SVG_Essentials
https://de.wikibooks.org/wiki/Svg
https://jwatt.org/svg/authoring/
https://www.w3.org/TR/SVG/
https://www.w3.org/TR/SVGMobile12/

**Comment by dbareiro** [comment]
Hi, Manfred!

Thank you for your prompt reply and the resources. I think I've been able to get the result I needed with the following code:

```
g = dwg.g(style="font-weight:bold;font-family:DejaVu Sans")
g.add(dwg.text(element, insert=(x, y), fill=color))
dwg.add(g)
```
It seems to work, although I don't know if it will be the best (or only) way to implement it.

Thanks for your time.

Kind regards,
Daniel
