### ISSUE TITLE
New lines within a text block

### ISSUE THREAD

**Issue by dbareiro** [mozman/svgwrite#11]
Hi, Manfred!

I'm reading the SVG and svgwrite documentation to see how I could create a multi-line text block, but I'm not sure how I could do it.

Maybe this could be done with tspan?

https://pythonhosted.org/svgwrite/classes/text.html#svgwrite.text.TSpan

Or maybe I should use something like `textLength`?

http://commons.oreilly.com/wiki/index.php/SVG_Essentials/Text#Setting_textLength

Any recommendation is appreciated.

Thanks in advance.

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi again, Manfred.

I've made some progress with this code:

```
paragraph = dwg.add(dwg.g(font_family="DejaVu Sans"))
atext = dwg.text(row[3], insert=(x, y), font_size=11, style="font-weight:bold", fill=color)

y = y + 10
atext.add(dwg.tspan(row[0] + ' : ' + row[4] + ', ' + row[6] + ', ' + row[7], insert=(x,y), font_size=8, fill=color))
paragraph.add(atext)

# Set separation for new block of lines
y = y + 35
```

Here the idea is that the first line has a height of 11 and it is bold, while the second line has a height of 8 and it is not bold. With that code both heights seem to show as expected, but both lines seems to be in bold when only the first should be. So here I think I'm missing something. Maybe my error is due to always using `atext` and so the second line is also in bold.

Another thing I am observing is that the second line is not editable when the idea is that it is also editable. Is this a consequence of using `tspan`?

Thanks in advance for your time.

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi again, Manfred.

I made some changes to the code and now each line is a `tspan`:
```
paragraph = dwg.add(dwg.g(font_family="DejaVu Sans"))
atext = dwg.text("", insert=(x, y))
atext.add(dwg.tspan(row[3], insert=(x, y), font_size=11, style="font-weight:bold", fill=color))

y = y + 10

atext.add(dwg.tspan(row[0] + ' : ' + row[4] + ', ' + row[6] + ', ' + row[7], insert=(x, y), font_size=8, fill=color))

paragraph.add(atext)

# Set separation for new block of lines
y = y + 35
```
On that way each line has its height of letter and different style and I can handle independently the height of each line and the bold text. So I thinks to have solve one of the problems I was having.

However I have not been able to make the second line editable. Any recommendation is appreciated.

Thanks in advance for your time.

Kind regards,
Daniel

**Comment by 12edge** [comment]
You may want to read about SVG baselines at [http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Baselines](http://tavmjong.free.fr/SVG/TEXT_SYDNEY_2016/#Baselines)
Inkscape is getting some font features which you can read about [http://tavmjong.free.fr/blog/?p=1442](http://tavmjong.free.fr/blog/?p=1442)
I am suggesting that svgwrite can create svg but is likely not the easiest way to create textual documents. Overall SVG is not good at doing much more than basic textual work.
- Lawrence Tattrie
