### ISSUE TITLE
Use <pageset> and <page>

### ISSUE THREAD

**Issue by rocordial** [mozman/svgwrite#12]
I try to make some quiz forms for optical recognition with responder name preprinted.
I would like to generate one svg file with each form on a page than "print' it to a multipage pdf from Chrome.
Is there support for the `<pageset>` and `<page>` tags?
Couldn't find it in the docs.

Thank you for this great libray!

**Comment by rocordial** [comment]
Sorry,

Seems like pageSet and page tags are just a w3c working draft yet.
So do you have any suggestion about multipages in svg documents?

**Comment by 12edge** [comment]
[https://www.w3.org/TR/2004/WD-SVG12-20041027/multipage.html ](https://www.w3.org/TR/2004/WD-SVG12-20041027/multipage.html ) 
The pageSet and page elemets are "SMIL time containers" but most browsers do not or will not be implementing any SMIL. 
See also:
[http://wiki.inkscape.org/wiki/index.php/Multipage](http://wiki.inkscape.org/wiki/index.php/Multipage)

>  Currently, Inkscape does not have multipage support. The main reason is that the current SVG standard does not support multipage documents. This feature was proposed in the SVG revision 1.2, but for now got dropped in the next coming version SVG 2.0. 

 [https://github.com/w3c/svgwg/issues/157](https://github.com/w3c/svgwg/issues/157)

Perhaps using a general purpose word processing application would help you. I recommend this issue be closed as it cannot be done by svgwrite.
- Lawrence Tattrie
