### ISSUE TITLE
How to use rotation transform?

### ISSUE THREAD

**Issue by matthias-k** [mozman/svgwrite#16]
I am trying to add a rotation transform to a text. From the documentation it appears this should be possible via the `Transformation.rotate` mixin, but I cannot figure out how to use it. So far I was only able to do

```lang=python
drawing.text(text="foo", insert=(0, 0), transform="rotate(90, 0, 0)")
```

But constructing this string from data doesn't feel right ;).

**Comment by mozman** [comment]
Mixin methods are methods of the created entity:

    text = drawing.text(text="foo", insert=(0, 0))
    text.rotate(angle=90, center=(0, 0))
