### ISSUE TITLE
Creating Inkscape layers with svgwrite

### ISSUE THREAD

**Issue by ao2** [mozman/svgwrite#17]
Hi,

This is not really an issue report but rather more of a comment, feel free to close it right away :)

In case someone needed to create Inkscape layers with svgwrite here is an InkscapeDrawing class which extends the validator to recognize the required attributes:
https://git.ao2.it/experiments/svgwrite_inkscape_drawing.git/blob/HEAD:/svgwrite_inkscape_drawing.py

My use case is to create some baseline svg file programmatically with svgwrite and then customize it in inkscape; and having objects grouped into layers makes the customization a little easier.

Thanks,
   Antonio

**Comment by trew** [comment]
@ao2 Thanks, man. This class was exactly what I was looking for in my pretty similar use case.

**Comment by ao2** [comment]
Ah, I'm glad it's useful to someone else.

JFTR I used this to create Inkscape SVGs to:
* edit flexagons:
  - https://ao2.it/130
  - https://twitter.com/ao2it/status/958665312639111171
  - https://twitter.com/ao2it/status/1012357163774283782
* make automatic isometric projections:
  - https://twitter.com/ao2it/status/1013796546557763587
  - https://www.youtube.com/watch?v=t4xlbcNt9SI

**Comment by mozman** [comment]
Added an inkscape extension for layer support to just released svgwrite 1.2.0

docs: https://svgwrite.readthedocs.io/en/latest/extensions/inkscape.html

**Comment by ao2** [comment]
Cool, I didn't expect this to become part of svgwrite, thank you @mozman.

May I ask why you chose the extension mechanism instead of a new class?
Maybe because it can be used together with other possible future extensions?

**Comment by mozman** [comment]
Yes, for combining with other extensions and future svg versions. But that does not mean I have planned other extensions nor support for svg2 in the near future.

**Comment by ao2** [comment]
Thanks.
