### ISSUE TITLE
Is `debug` the best name for this parameter?

### ISSUE THREAD

**Issue by SnoopJeDi** [mozman/svgwrite#19]
I'm curious about the naming of the [`debug`](https://github.com/mozman/svgwrite/blob/master/svgwrite/base.py#L49-L56) parameter on subclasses of `BaseElement`. I helped a user this week with a [somewhat mysterious slowdown](https://twitter.com/inconvergent/status/970756945937424385) of their SVG generation, which turned out to be solved by explicitly turning this validation behavior off.

The name `debug` to me suggests that this is opt-in behavior intended for diagnosing buggy behavior, so the default behavior of having this turned on is unintuitive to me. Would it make sense to perhaps rename this parameter to `validate` to better match its behavior?

**Comment by mozman** [comment]
This is not a good idea for a basic parameter in a package published since 2010.
