### ISSUE TITLE
Use of parametric svg in parser

### ISSUE THREAD

**Issue by kvnamipara** [mozman/svgwrite#20]
I want to parse parametric SVG and reproduce corresponding SVG file as user requirement. Can we use that fact and implement it using `svgwrite`.
Please let me know if you have any suggestions for the same.

**Comment by mozman** [comment]
svgwrite is MIT licensed, you can do what you want.

**Comment by kvnamipara** [comment]
@mozman Any suggestions on how to implement it. Thanks

**Comment by mozman** [comment]
no
