### ISSUE TITLE
Some svg files appear blank.

### ISSUE THREAD

**Issue by aris-ang** [mozman/svgwrite#22]
Hello there! Is there a known issue when viewing svg files? I have made a module which reads coordinates from an xml file and connects them using polylines and polygons in svgwrite. While some files are saved perfectly well and can be viewed on my browser, other files appear blank even though the .svg files contains the code that is required.

Thanks in advance.

**Comment by YPares** [comment]
Same problem here. I'm trying the basic example from the README and it doesn't work. SVG appears blank.

**Comment by aris-ang** [comment]
Hi again. I actually managed to overcome the problem. I used wrong dimensions when creating a svgwrite.Drawing object, so it failed placing points due to the fact that their coordinates where bigger than the total height of the file. @YPares, i suggest you check on that too in case you are having the same problem.
