### ISSUE TITLE
how to specify xlink attributes?

### ISSUE THREAD

**Issue by creisle** [mozman/svgwrite#3]
For the attributes that contain a hyphen I can specify using underscore. Is there a similar convention for specifying xlink attributes? i.e. xlink_title? I want to be able to specify the title for a hyperlink but I haven't been able to do so

**Comment by mozman** [comment]
Docs are here: http://svgwrite.readthedocs.io/en/latest/classes/mixins.html#xlink-mixin

for usage see tests: https://github.com/mozman/svgwrite/blob/master/tests/test_xlink.py
