### ISSUE TITLE
encoding error when using pretty=True

### ISSUE THREAD

**Issue by rompic** [mozman/svgwrite#35]
Hi!

Great library.
I'm experiencing an encoding error on python 2.7 if I use pretty=True, though:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 214-216: ordinal not in range(128)

> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> import svgwrite
> 
> dwg=svgwrite.Drawing()
> dwg.add(dwg.text("•••", insert=(0,0)))
> dwg.saveas('test' + ".svg", pretty=True)

any hints?
thanks in advance,
Roman

**Comment by rompic** [comment]
it works if
        xml_string = self.tostring()
is changed to
        xml_string = self.tostring().encode("utf-8")

in https://github.com/mozman/svgwrite/blob/master/svgwrite/drawing.py#L109

maybe you can have another look or point me in the right direction.

thanks in advance,
Roman

**Comment by mozman** [comment]
Sorry, this was an error in svgwrite, fixed in next release. But please use Python 3, the official Python 2 support ends 2020 and i will remove the Python 2 support from svgwrite soon.

**Comment by rompic** [comment]
Thanks for taking another look. Yes I will migrate to python3 asap. Just managed to get rid of a lot of other stuff with the help of svgwrite and svglib. Python 2 is next :)
