### ISSUE TITLE
animateColor will removed from SVG2 and animateColor doesn't run in many browsers

### ISSUE THREAD

**Issue by pythoniax** [mozman/svgwrite#39]
animateColor without a future - see: https://www.w3.org/2014/01/16-svg-minutes.html#item01

so i think it should be replaced by a common "<animate ... />" element.

In gecko browsers the following code don't work:
` <text id="text" x="150" y="30">
    here some text
    <animateColor
            attributeName="fill"
            attributeType="XML"
            id="text"
            repeatCount="indefinite"
            dur="20s"
            from="green"
            to="red"/>
</text>`

But this runs:
` <text id="text" x="150" y="30">
    here some text
    <animate
            id="text"
            attributeName="fill"
            attributeType="XML"
            begin="0;graphics.click"
            dur="20s"
            values="gray;darkred;red;cyan;lightcyan;green;purple;gray"
            calcMode="linear" />
  </text>`

**Comment by mozman** [comment]
svgwrite does not support SVG2
