### ISSUE TITLE
Setting `debug=False` does not reduce save times.

### ISSUE THREAD

**Issue by GeorgeTillisch** [mozman/svgwrite#40]
I was experiencing [this issue](https://github.com/mozman/svgwrite/issues/25) and tried setting `debug=False` when calling `svgwrite.Drawing()` as suggested, yet it does not appear to have any noticeable effect on save times.

The slow time is definitely a result of calling `tostring()` during the save process.

Any help would be greatly appreciated.

**Comment by clbarnes** [comment]
Is this closed as a wontfix or did you find some way of reducing save times?
