### ISSUE TITLE
paint-order attribute?  SVG2?

### ISSUE THREAD

**Issue by cwaldbieser** [mozman/svgwrite#44]
#! /usr/bin/env python

    import svgwrite

    def main():
        """
        Run the program.
        """
        dwg = svgwrite.Drawing(profile='full', size=(1000, 1000), viewBox='-500 -500 1000 1000', debug=True)
        g = dwg.g()
        g['paint-order'] = "stroke full"

    if __name__ == "__main__":
        main()

Running the above results in:

    ValueError: Invalid attribute 'paint-order' for svg-element <g>.

This seems to be [part of SVG2.](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order)  Is SVG2 supported by svgwrite?

**Comment by mozman** [comment]
SVG2 is not supported
