### ISSUE TITLE
<text> initialization method's x, y arguments don't accept decimals 

### ISSUE THREAD

**Issue by darthglowball** [mozman/svgwrite#49]
Hi,

`some_drawing_object.text(text = "hi", y = "21.838867")` triggers the validator2 module error handler functions:
`TypeError: '2 1 . 8 3 8 8 6 7' is not a valid value for attribute 'y' at svg-element <text>.`

For some reason these spaces inbetween digits are added in the error message.
Using the update method on a text element to do the same thing works fine, however.

**Comment by alexn11** [comment]
Are you sure that you're using this right? Seems like y should be a list of numerical values.
`some_drawing_object.text(text="hi",y=[21.1,])` works fine.

**Comment by darthglowball** [comment]
@alexn11 while `y=[21.1]` or `y=[21.1,]` work, the issues I have are inconsistency:
1) instancing a rect does allow `y="21.1"` and an integer in the string as an argument, while a text element only allows `y="21"` but no decimal in the string as argument.
2) The rect.update and text.update methods both allow setting integer and decimals in the strings
3) A text initialization argument such as `y="21"` works (no error) as a string, but it doesn't work as an int (error), while in the rect's instantiation method both argument types work (ateast, there's no error).

Also, check the y attribute in the output SVG file (through drawing's save method) when a text element is instanced with `y="21"`: spaces are added for some reason between each digit, and there's no error.

**Comment by alexn11** [comment]
It's unclear from the documentation how this supposed to work but in my opinion you should only pass numerical values to numerical arguments. The coordinates should be numbers and not string. My guess is that you've been lucky with other functions because of loose typing.

**Comment by darthglowball** [comment]
@alexn11, I think that having both element initialization argument types are beneficial: if you want speed, you take the float, and if you want correspondence with the DOM (document.setAttribute("myobject", "myattribute")) and XML (<rect x="100" y="20.43"/>) - which may be faster when you directly want to store your SVG after creation or attribute setting - you use the string.
