### ISSUE TITLE
text-decoration doesn't accept multiple decorations

### ISSUE THREAD

**Issue by kyamagu** [mozman/svgwrite#5]
I get the following `TypeError` when doing `tspan['text-decoration'] = 'underline line-through'`:

    TypeError: 'underline line-through' is not a valid value for attribute 'text-decoration' at svg-element <tspan>.

I believe [`text-decoration`](https://github.com/mozman/svgwrite/blob/master/svgwrite/data/full11.py#L760) should accept `types = ['list-of-name']` or there should be more strict checking. [The SVG spec allows multiple decorations.](https://www.w3.org/TR/SVG/text.html#TextDecorationProperty)

**Comment by mozman** [comment]
I don't think you can combine different text-decoration styles like underline and strike-through.

  value = none | [ underline || overline || line-through || blink ] | inherit

There is no explanation how to read this definition, but I found another definition at mozilla.org:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-decoration

  value = none | underline | overline | line-through | blink | inherit

This definition is clear: just one of them is allowed.

I think even if it is allowed by the SVG standard to use multiple text-decorations - it is not supported by any browser. But do some test with a plain SVG doc and a text editor.

**Comment by kyamagu** [comment]
@mozman `||` means concat. I can confirm the following renders all decorations in Chrome, Firefox, Safari on macOS.

```svg
<?xml version="1.0" encoding="utf-8" ?>
<svg baseProfile="full" height="240" version="1.1" width="240" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs />
    <text x="10" y="40" font-size="36" text-decoration="none">decorated text</text>
    <text x="10" y="80" font-size="36" text-decoration="underline">decorated text</text>
    <text x="10" y="120" font-size="36" text-decoration="overline">decorated text</text>
    <text x="10" y="160" font-size="36" text-decoration="line-through">decorated text</text>
    <text x="10" y="200" font-size="36" text-decoration="underline overline line-through">decorated text</text>
</svg>
```

**Comment by mozman** [comment]
Thank you - I will change the validator, but I will need some time for that.

**Comment by kyamagu** [comment]
@mozman That'll be great, thanks :)

**Comment by mozman** [comment]
Question!

For text-decoration="inherit underline overline line-through" Chrome/Firefox just ignores the appended decoration types. But according to SVG standard (value = none | [ underline || overline || line-through || blink ] | inherit) my validator should raise an exception.

@kyamagu - Is raising an exception for this case an expected behavior for you?

**Comment by kyamagu** [comment]
@mozman Yes, probably raising an exception is the expectation here, since the current design is already doing that for other errors.

**Comment by mozman** [comment]
release 1.1.11 fix this issue
