### ISSUE TITLE
'auto' is not a valid value for attribute 'rotate' at svg-element <animateMotion>

### ISSUE THREAD

**Issue by SurfChriz** [mozman/svgwrite#55]
Hi everybody,

like the topic already says: After having a line like this:
`dwg.animateMotion(anim_path, dur='15s', rotate='auto')`
I get a TypeError saying:
`'auto' is not a valid value for attribute 'rotate' at svg-element <animateMotion>`

While trying:
`dwg.animateMotion(anim_path, dur='15s', rotate='5')`
works just fine. I think validator2.py maybe sorting out strings? (just a guess)

The docs and the svg specs say that 'auto' should be a valid argument here.

**Comment by mozman** [comment]
You are using the wrong SVG version 1.2 Tiny, which do not support ` 'auto'` for attribute `rotate`.

**Comment by SurfChriz** [comment]
You are completely right!
Thanks for clarification and the quick response!
