### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by grhawk** [mozman/svgwrite#56]
Hi, this is a very nice job. I would like to use this package but I need to be sure about the licensing: the LICENSE file is a clear MIT while the file `svgwrite/shapes.py` contains a clear GPL. Is this wanted? If not, could you pls correct it?

Another issue are the font files in the `example`... they have another different license. Is this also wanted? 

Thank you!

**Comment by mozman** [comment]
Fixed `shapes.py` license, files in `examples/ltattrie` are not mine and the font file also, but examples are not automatically installed by `pip`. If you are copying the files, you have to solve this problem by yourself (e.g. deleting the files)

**Comment by grhawk** [comment]
Thank you very much!

**Comment by grhawk** [comment]
Do you plan to release a new version with the corrected licensing? (that would be very useful to me :D )

**Comment by mozman** [comment]
released v1.3.1

**Comment by grhawk** [comment]
thank you!
