### ISSUE TITLE
Pretty-printing should not pretty-print inside text elements

### ISSUE THREAD

**Issue by mitar** [mozman/svgwrite#58]
Because adding white-space to inside of text elements changes what is being rendered. :-(

**Comment by mozman** [comment]
Pretty print is done by `xml.dom.minidom` and should only touch the XML structure not the content.

**Comment by mitar** [comment]
By definition it adds whitespace inside XML tags. But for `<text>` tags white-space is significant. Which leads to differences in how SVG is rendered.

**Comment by mitar** [comment]
So what I am trying to say is that maybe minidom is not the most suitable for XML.

**Comment by mitar** [comment]
I opened: https://bugs.python.org/issue37442

**Comment by Andrej730** [comment]
Moved to https://github.com/python/cpython/issues/81623
