### ISSUE TITLE
ICC-colors

### ISSUE THREAD

**Issue by MichaelMauderer** [mozman/svgwrite#6]
Is there support for using [ICC-colors ](https://www.w3.org/TR/SVGColor12/#icc-colors) instead of sRGB colours, e.g., as part of a `stroke` specification of a line?

If not, is this a planned feature?

**Comment by mozman** [comment]
I will put this feature on my todo list, but don't expect an implementation in the near future - this is 
 work for long winter nights ;).

**Comment by MichaelMauderer** [comment]
Is there a work around to disable validation of the currently supported
colour that would allow me to inject just the string I need so colour
attribute?

**Comment by mozman** [comment]
Turn off validation:
```
# for all entities
dwg = svgwrite.Drawing(filename=name, debug=False)

# for just one entity
dwg = svgwrite.Drawing(filename=name, debug=True)
dwg.add(dwg.circle(center=(0, 0), r=100, stroke='assign-whatever-you-want', debug=False))

```

But there is no support for assigning a color-profile.

**Comment by mozman** [comment]
I just noticed, color values like`fill="icc-color(...)"` was always suported

see tests: https://github.com/mozman/svgwrite/blob/13a0f95e262a317b3e2d01b05fff02e5133134b9/tests/test_full11_typechecker.py#L229
