### ISSUE TITLE
Automatic generation of clipping path IDs and referencing them

### ISSUE THREAD

**Issue by mitar** [mozman/svgwrite#60]
Similar to how group IDs are automatically generated and once can then reference them by Python object in `use`, something similar could be done for clipping paths.

```python
clip_path = drawing.clipPath()
drawing.defs.add(clip_path)
clip_path.add(drawing.rect(insert=(0, 0), size=(10, 10)))
drawing.circle((10, 10), 10, clip_path=clip_path)
```

One has to currently do:

```
drawing.circle((10, 10), 10, clip_path=clip_path.get_funciri())
```

Which is not documented either.

**Comment by mozman** [comment]
No changes or additions planned, the package should stay as it is -- forever.
