### ISSUE TITLE
Simplify example code

### ISSUE THREAD

**Issue by Overdrivr** [mozman/svgwrite#63]
Just a minor thing, I'm just having a look at this library, but I get the feeling the example is more intricate than it needs to. From the demo code:

```
import svgwrite

dwg = svgwrite.Drawing('test.svg', profile='tiny')
dwg.add(dwg.line((0, 0), (10, 0), stroke=svgwrite.rgb(10, 10, 16, '%')))
dwg.add(dwg.text('Test', insert=(0, 0.2), fill='red'))
dwg.save()
```

Why does a Drawing **instance** + calling dwg.add is required to create a line ?
It feels duplicate.

This version removes this duplicate behavior:

```
import svgwrite
from svgwrite.shapes import Line
from svgwrite.text import Text

dwg = svgwrite.Drawing('test.svg', profile='tiny')
dwg.add(Line((0, 0), (10, 0), stroke=svgwrite.rgb(10, 10, 16, '%')))
dwg.add(Text('Test', insert=(0, 0.2), fill='red'))
dwg.save()
```

Maybe it already does, but also it would be nice to group common SVG primitives under the root svgwrite namespace to simplify imports.

**Comment by mozman** [comment]
The factory functions of object `dwg` to create new entities is the key to support validation for different SVG versions. Importing all required classes is Java style, in svgwrite you don't have to know where the classes are implemented and the implementation can be changed easy in future version of svgwrite without braking user code.
