### ISSUE TITLE
Make Units extensible

### ISSUE THREAD

**Issue by jamadagni** [mozman/svgwrite#65]
Hello. Thank you for **svgwrite**!

I tried something like: ```unit = 0.75 * inch``` because my application uses this length as a unit, but it is not further possible to multiply this to denote 2 units 3 units etc. This is because doing `0.75 * inch` creates a simple string and multiplying only lengthens the string. Something like the following in `__init__.py` would be much more preferable, which only converts to string at the last minute: 

```Python
class Unit(object):
    """ Add units to values.
    """
    def __init__(self, unit='cm', multiplier=1):
        """ Unit constructor

        :param str unit: specify the unit string
        """
        self._unit = unit
        self._mul = multiplier

    def __rmul__(self, other):
        """ create new unit by multiplying current unit with 'other'. (e.g. 5*cm => '5cm') """
        return Unit(self._unit, self._mul * other)
    
    def __str__(self):
        """ create a string representing this unit """
        return "%s%s" % (self._mul, self._unit)
```

but I am unable to provide a PR because I do not know the other implications of this change including how to change `__call__` in the same file, hence leave it to the developer.

Thank you!

**Comment by mozman** [comment]
No changes or additions planned, the package should stay as it is -- forever.
