### ISSUE TITLE
Invalid attribute 'textLength' for svg-element <text>

### ISSUE THREAD

**Issue by xeon1988** [mozman/svgwrite#68]
`import svgwrite
from svgwrite import cm, mm
dwg = svgwrite.Drawing('test.svg', height=8*cm, width=8*cm, profile='tiny')
dwg.add(dwg.ellipse(center=(5*cm, 5*cm), r=('4cm', '3cm'), stroke='red', fill='none', stroke_width='1mm'))
dwg.add(dwg.text('91150100114153398C', insert=(2*cm, 6*cm), textLength='20', lengthAdjust='spacingAndGlyphs',
                 fill='red', font_family='Arial', font_weight='bold', font_size='20', stroke_width='0.5'))
dwg.save()`

**Comment by timgitsit2** [comment]
What was the solution?
