### ISSUE TITLE
data attributes

### ISSUE THREAD

**Issue by kyamagu** [mozman/svgwrite#7]
Thanks for the great tool :)

This is a feature request. Currently the validator throws an exception for data-* attributes. Maybe attributes starting with `data-` should be ignored for validation, as SVG2 draft allows that.

* https://svgwg.org/svg2-draft/struct.html#DataAttributes
* [https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*)

**Comment by mozman** [comment]
svgwrite does not support SVG2, just SVG 1.1 and SVG Tiny 1.2

**Comment by jonathan-s** [comment]
I was looking for this too. So just chipping in my vote for this. Otherwise, would you recommend another library?

**Comment by jonathan-s** [comment]
@mozman, I solved this in the version I forked. Let me know if you want this back into the library.
