### ISSUE TITLE
allow white spaces in attributes

### ISSUE THREAD

**Issue by rheinheimer** [mozman/svgwrite#8]
I am trying to add multiple classes to my elements, to style via CSS, but get an error when doing so. It seems you cannot have white spaces in the attributes. Example:
```
mycircle['class'] = "class1 class2"
```
This throws an error. The workaround is to use groups, but a) that's harder and b) this still limits styling flexibility. So, I suggest allowing spaces.

**Comment by mozman** [comment]
Can not reproduce the error:
 - `circle = dwg.circle(center=(0, 0), r=2, class_='class1 class2')` works
 - `circle['class'] = 'class1 class2'`  also works
