### ISSUE TITLE
Polygons with holes

### ISSUE THREAD

**Issue by loicland** [mozman/svgwrite#82]
Hi, and thanks for the helpful lib.

Is it possible to add holes in the polygons?

**Comment by 12edge** [comment]
Yes, svg allow holes and so does svgwrite. You will need to read up on the even / odd fill rule. Imagine a circle such as a clock face with the path going clockwise. Now imagine adding a smaller circle inside with the path going anti-clockwise. The smaller circle will create a hole in the larger circle. 
See [https://www.w3.org/TR/SVG2/painting.html#WindingRule](https://www.w3.org/TR/SVG2/painting.html#WindingRule)

**Comment by loicland** [comment]
Thanks, figured it out!
