### ISSUE TITLE
Allow spaces for comma separated RGB values in rgb()

### ISSUE THREAD

**Issue by villares** [mozman/svgwrite#84]
Thank you for the wonderful library!
According to the SVG documentation here https://www.w3.org/TR/SVG11/types.html#syntax
`rgb(255, 255, 0)` should be valid syntax for color attributes. Could we add some space removing code to allow for it?

**Comment by 12edge** [comment]
Please supply some code which is causing an error.  I have used in the past something like this:
```
img_for_colour = 'rgb(255, 255, 255)'
dwg.add(dwg.rect(insert=(0, 0), size=('100%', '100%'), fill=img_for_colour))
```

**Comment by villares** [comment]
I worked! My bad!
