### ISSUE TITLE
svgwrite does not accept `values' for `fill'/`stroke' in `animate'

### ISSUE THREAD

**Issue by dword1511** [mozman/svgwrite#9]
The following code
```
animate.Animate('fill', dur = '1.7s', begin = '2s', fill = 'freeze',
  values = '#000000;#0000ff;#00ff00;#ff0000',
  keyTimes = '0;0.2;0.4;1')
```
does not pass svgwrite's type check. After removing the type check, the svg file generated works as expected in Chrome and Firefox.

**Comment by mozman** [comment]
fixed in next svgwrite release v1.1.12
