### ISSUE TITLE
How to get the actual size of text element?

### ISSUE THREAD

**Issue by philipsd6** [mozman/svgwrite#99]
Given a central point, I create a headline with given text, and I center the text vertically and horizontally on that point with:
```
        dominant_baseline="middle",
        text_anchor="middle",
```
I need to have a box of the same size/ratio as the text to block out the background. But since the text is dynamic, I cannot know what the width of the text is without some way to calculate it based on the text element I create.

How do I do this?

**Comment by philipsd6** [comment]
I guess this is the same as #54, but there's no answer there!

**Comment by mozman** [comment]
`svgwrite` is not rendering engine and knows nothing about text fonts.

**Comment by philipsd6** [comment]
I guess that makes sense. All I wanted was to "punch out" space for my text, so I handled it by creating a mask from my text:


```python
from svgwrite.masking import Mask
mask = Mask()
# White for full image size
mask.add(dwg.rect(insert=(0,0), size=(size.width, size.height), fill="white"))
# Black to punch out a text shaped hole
mask.add(my_text.copy().fill("black").stroke("black", width=0.2))
```

Then I just made sure my background referenced the mask with:
```python
mask=mask.get_funciri()
```
Maybe this is a technique that could be documented more clearly, or on an FAQ or something?
